# Generated by Django 3.2.5 on 2021-07-22 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Profile_Picture', models.ImageField(default='user.png', upload_to='Profile_Pics')),
                ('Address', models.CharField(max_length=300)),
                ('City', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=30)),
                ('Pin_Code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=300)),
                ('Role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('Image', models.ImageField(upload_to='Post_Images')),
                ('Summary', models.CharField(max_length=500)),
                ('Content', models.CharField(max_length=1000)),
                ('DateTimeOfPoast', models.DateTimeField()),
                ('Draft', models.BooleanField(default=False)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doctor')),
            ],
            options={
                'ordering': ['-DateTimeOfPoast'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Profile_Picture', models.ImageField(default='user.png', upload_to='Profile_Pics')),
                ('Address', models.CharField(max_length=300)),
                ('City', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=30)),
                ('Pin_Code', models.IntegerField()),
                ('User_Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_master')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='User_Master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_master'),
        ),
        migrations.AddField(
            model_name='category',
            name='Doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doctor'),
        ),
    ]
