# Generated by Django 3.2.5 on 2021-07-19 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=300)),
                ('Role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Profile_Picture', models.ImageField(default='user.png', upload_to='Profile_Pics')),
                ('Address', models.CharField(max_length=300)),
                ('City', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=30)),
                ('Pin_Code', models.IntegerField()),
                ('User_Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_master')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Profile_Picture', models.ImageField(default='user.png', upload_to='Profile_Pics')),
                ('Address', models.CharField(max_length=300)),
                ('City', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=30)),
                ('Pin_Code', models.IntegerField()),
                ('User_Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_master')),
            ],
        ),
    ]
