# Generated by Django 3.2.5 on 2021-07-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Status',
            field=models.CharField(blank=True, default=' ', max_length=20),
        ),
    ]
