# Generated by Django 3.2.5 on 2021-07-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Status',
            field=models.CharField(blank=True, default='Pending', max_length=20),
        ),
    ]
