# Generated by Django 3.2.5 on 2021-07-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='End_Time_of_Appointment',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Start_Time_of_Appointment',
            field=models.TimeField(),
        ),
    ]
